[tool.poetry]
name = "california-housing-optuna"
version = "0.1.0"
description = ""
authors = ["marianaph6 <mariana1996.mph@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
